### ISSUE TITLE
chrome 56 breaks js in kiwix-serve

### ISSUE THREAD

**Issue by tim-moody** [kiwix/tools#1]
on access to even an old zim like ted_en_science_2015-02/ jquery fails to initialize with

jquery.js:9790 Uncaught SyntaxError: Invalid or unexpected token

this is the end of the file and there are two junk characters.

problem does not occur in latest FF or chrome 55 and earlier.

breaks search, and on ted science videos do not appear.

**Comment by tim-moody** [comment]
Forgot to mention this is legacy kiwix server 0.9

**Comment by Skylsmoi** [comment]
I have the same issue. Only on Chrome, FF runs fine.
I am running Chrome 56 (64bits) on Debian Jessie.
The 2 junk chars appears on every ressources (html, css and js)

**Comment by mgautierfr** [comment]
This issue is on the wrong repository.
I've opened a issue there : https://github.com/kiwix/kiwix-tools/issues/15

I'm closing this issue. Please continue the discussion there.
